//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.01 at 11:15:41 PM ICT 
//
package thienVN.JaxB;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for House complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="House">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{thien.xsd}Phone"/>
 *         &lt;element name="area" type="{thien.xsd}Double"/>
 *         &lt;element name="electricPrice" type="{thien.xsd}Double"/>
 *         &lt;element name="waterPrice" type="{thien.xsd}Double"/>
 *         &lt;element name="rentPrice" type="{thien.xsd}Double"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "House", propOrder = {})
@XmlRootElement(name = "house")
public class House {

    @XmlElement(required = true)
    protected String image;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String address;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected String area;
    @XmlElement(required = true)
    protected String electricPrice;
    @XmlElement(required = true)
    protected String waterPrice;
    @XmlElement(required = true)
    protected String rentPrice;
    @XmlElement(required = true)
    protected BigDecimal latitude;
    @XmlElement(required = true)
    protected BigDecimal longitude;
    @XmlElement(required = true)
    protected BigDecimal distance;
    @XmlElement(required = true)
    protected BigDecimal point;
    private int id;

    public House() {
    }

    public House(int id, String image, String url, String name, String address, String phone, String area, String electricPrice, String waterPrice, String rentPrice, BigDecimal latitude, BigDecimal longitude) {
        this.id = id;
        this.image = image;
        this.url = url;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.area = area;
        this.electricPrice = electricPrice;
        this.waterPrice = waterPrice;
        this.rentPrice = rentPrice;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the value of the image property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the url property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the phone property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the area property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setArea(String value) {
        this.area = value;
    }

    /**
     * Gets the value of the electricPrice property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getElectricPrice() {
        return electricPrice;
    }

    /**
     * Sets the value of the electricPrice property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setElectricPrice(String value) {
        this.electricPrice = value;
    }

    /**
     * Gets the value of the waterPrice property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getWaterPrice() {
        return waterPrice;
    }

    /**
     * Sets the value of the waterPrice property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setWaterPrice(String value) {
        this.waterPrice = value;
    }

    /**
     * Gets the value of the rentPrice property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRentPrice() {
        return rentPrice;
    }

    /**
     * Sets the value of the rentPrice property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRentPrice(String value) {
        this.rentPrice = value;
    }

    /**
     * Gets the value of the latitude property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

    public BigDecimal getDistance() {
        return distance;
    }

    public void setDistance(BigDecimal distance) {
        this.distance = distance;
    }

    public BigDecimal getPoint() {
        return point;
    }

    public void setPoint(BigDecimal point) {
        this.point = point;
    }
    
    
}
